### ISSUE TITLE
Move job dependent globals in scheduler.py to config/job_definitions.yaml, dependencies in spider_install.py to config/plugins.yaml

### ISSUE THREAD

**Issue by Simon-van-Diepen** [TUDelftGeodesy/caroline#225]
Plugins as:
```
plugins:
  github:
    Namexxx: 
      repo: xxx
      branch: xxx
  tarball:
     Namexxx: locationxxx (with plugins archive directory link)
```

Job definitions as
```
jobs:
  depsi:
    Two-letter-id: xxx
    Sbatch-args: xxx
    Bash-file: xxx
    Dependency: xxx
   Xxx
```
